### ISSUE TITLE
get_frequency function error

### ISSUE THREAD

**Issue by xnejed07** [physionetchallenges/python-classifier-2021#1]
Hi,
I found error in helper code in get_frequency function. Your code is missing enumerate and split string is incorrect (': ').
I am sending corrected version of get_frequency function below:
def get_frequency(header):
    frequency = None
    for i, l in enumerate(header.split('\n')):
        if i==0:
            try:
                frequency = float(l.split(' ')[2])
            except:
                pass
        else:
            break
    return frequency

**Comment by matthewreyna** [comment]
Thank you for catching this issue and sharing a correction.
