### ISSUE TITLE
Header transcription incomplete

### ISSUE THREAD

**Issue by adrian-camp** [physionetchallenges/python-classifier-2021#4]
Hi,

I found that when doing the lead conversion in extract_leads_wfdb.py the headers are copied from a 12 lead version to a sublead version in an incomplete way. The lines for each channel are missing ".mat" after the file name. This causes problems with other wfdb functions such as rdsamp when trying to read the files and headers. This problem is solved by removing or commenting out line 75 (entries[0] = recording_id) in extract_leads_wfdb.py.

Example of header conversion as of now:

Original Header (12 leads):

A0001 12 500 7500 12-May-2020 12:33:59
A0001.mat 16+24 1000/mV 16 0 28 -1716 0 I
A0001.mat 16+24 1000/mV 16 0 7 2029 0 II
A0001.mat 16+24 1000/mV 16 0 -21 3745 0 III
A0001.mat 16+24 1000/mV 16 0 -17 3680 0 aVR
A0001.mat 16+24 1000/mV 16 0 24 -2664 0 aVL
A0001.mat 16+24 1000/mV 16 0 -7 -1499 0 aVF
A0001.mat 16+24 1000/mV 16 0 -290 390 0 V1
A0001.mat 16+24 1000/mV 16 0 -204 157 0 V2
A0001.mat 16+24 1000/mV 16 0 -96 -2555 0 V3
A0001.mat 16+24 1000/mV 16 0 -112 49 0 V4
A0001.mat 16+24 1000/mV 16 0 -596 -321 0 V5
A0001.mat 16+24 1000/mV 16 0 -16 -3112 0 V6
#Age: 74
#Sex: Male
#Dx: 59118001
#Rx: Unknown
#Hx: Unknown
#Sx: Unknown

Header after converting to 2 leads:

A0001 2 500 7500 12-May-2020 12:33:59
A0001 16+24 1000/mV 16 0 7 2029 0 II
A0001 16+24 1000/mV 16 0 -596 -321 0 V5
#Age: 74
#Sex: Male
#Dx: 59118001
#Rx: Unknown
#Hx: Unknown
#Sx: Unknown

Expected header conversion:

A0001 2 500 7500 12-May-2020 12:33:59
A0001.mat 16+24 1000/mV 16 0 7 2029 0 II
A0001.mat 16+24 1000/mV 16 0 -596 -321 0 V5
#Age: 74
#Sex: Male
#Dx: 59118001
#Rx: Unknown
#Hx: Unknown
#Sx: Unknown

**Comment by matthewreyna** [comment]
Thanks for noticing this issue. I updated the `extract_leads_wfdb.py` script to fix this and a couple of other issues for `rdsamp` and other utilities. Please direct future questions and comments to the Challenge email account.
