### ISSUE TITLE
extract_leads_wfdb.py bug

### ISSUE THREAD

**Issue by acmilannesta** [physionetchallenges/python-classifier-2021#5]
Line 52 will report error.
 ```recording_ids = set(full_lines[i].split(' ')[0].split('.mat')[0] for i in range(1, num_full_leads+1))``` 
Suggest changing to
 ```recording_ids = set(full_lines[i].split(' ')[0] for i in range(1, num_full_leads+1))```

**Comment by matthewreyna** [comment]
Thank you for this feedback. This check caught an inconsistency in the training data and has been removed. Please direct future feedback to the Challenge forum and email address.
