### ISSUE TITLE
Working with submodules

### ISSUE THREAD

**Issue by wenh06** [physionetchallenges/python-classifier-2021#6]
In my entry repository, I add [another public repository](https://github.com/wenh06/torch_ecg) as a submodule which is re-used in other projects of mine. A mere `git clone` would NOT automatically clone the submodules, which would only be done after `git submodule update --init`. Otherwise, `ModuleNotFoundError` would be raised. I tried to add the following lines in the Dockerfile, but failed
```
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
RUN git submodule update --init --remote --recursive --merge --progress
```
when build in Docker Hub. However, Docker Hub is able to correctly handle the submodules.

Now I have to copy the submodule in a "backup" folder and import from it. Can you make working with submodules more easy? Thanks a lot!

**Comment by matthewreyna** [comment]
Thanks for this comment. This issue is not related to the example repository, and we are already discussing it over email and hope to find a speedy resolution. Please direct future comments and questions to the Challenge forum or email.
